/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Greg (https://sketchfab.com/gregoirebonnin)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/a380-plane-76786c9a9c834c0ba6ce8c323f7f93b8
Title: A380 plane
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh;
  };
  materials: {
    ["default.007"]: THREE.MeshStandardMaterial;
  };
};

const SCALE = .2
export function PlaneModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/models/a380_plane.glb") as GLTFResult;
  return (
    <group {...props} dispose={null} scale={[SCALE,SCALE,SCALE]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="A380_0" rotation={[Math.PI / 2, 0, 0]}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["default.007"]}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/a380_plane.glb");
